# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Theme Settings
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dr. Lucas Lasota
masthead_title: "About me"
description: This is the website of Lucas Lasota.
search: true

# Build settings
markdown: kramdown

# Outputting
permalink: /:categories/:year/:month/:day/:title:output_ext
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  #- jekyll-paginate # added by default by GitHub
  #- jekyll-gist # added by default by GitHub
  - jemoji # use emojis
  - jekyll-remote-theme # neded for minimal mistakes theme 
  - jekyll-sitemap # neded for minimal mistakes theme 
  - jekyll-include-cache # needed for minimal mistakes theme
  - jekyll-feed # neded for minimal mistakes theme


# Author Information
author:
  name   : Lucas Lasota
  avatar : /assets/images/lasota.png
  bio    : Free Software & IT Law
  email: lucaslasota@gmx.net
  github: lucaslasota
  links:
    - label: "Zotero"
      icon: "fa fa-book"
      url: "www.zotero.org/lucaslasota"

include:
  - _pages

# Page default settings
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

footer:
  rss: false
